-- 코드를 작성해주세요
SELECT ID, FISH_NAME, MAX_LENGTH AS LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO NI ON I.FISH_TYPE = NI.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE) M ON I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
ORDER BY ID;